# Author: Aaron Munro Allen
# Date: 2021-11-15
# Description:
#   Function to extract data from the "feat.mat" file generated by the Caltech FlyTracker
#   package written in Matlab. It may not matter, but this file assumes that "id_correction"
#   has been run from https://github.com/aaron-allen/goodwin-lab-tracking.


extract_feat_data <- function(file_path) {

    ufmf_feat <- R.matlab::readMat(file_path)
    
    # names
    feat_names <- unlist(ufmf_feat[["feat"]][[1]])    
    ufmf_feat[["feat"]][[2]][[8]] <- ufmf_feat[["feat"]][[2]][[1]]
    ufmf_feat[["feat"]][[2]][[8]][[1]][1,1] <- "NA"
    feat_units <- unlist(ufmf_feat[["feat"]][[2]])

    # data
    for (i in 1:dim(ufmf_feat[["feat"]][[3]])[3]) {
        if (i == 1) {
            feat_data <- list()
        }
        for (ii in 1:dim(ufmf_feat[["feat"]][[3]])[1]) {
            if (ii == 1) {
                feat_data_feature <- list()
            }
            feat_data_feature[[ii]] <- tibble::tibble(Fly_Id = ii,
                                              Feature = feat_names[[i]],
                                              Units = feat_units[[i]],
                                              Value = ufmf_feat[["feat"]][[3]][ii,,i]
            )
        }
        feat_data[[i]] <- dplyr::bind_rows(feat_data_feature)
    }
    feat_data <- dplyr::bind_rows(feat_data)

    return(feat_data)
}





