# Author: Aaron Munro Allen
# Date: 2021-11-15
# Description:
#   Function to extract data from the JAABA scores files generated by the JAABA package written in Matlab.
#   This function assumes that "id_correction" has been run from https://github.com/aaron-allen/goodwin-lab-tracking.
#   The files are of the form "scores_<behaviour>_id_corrected.mat".


extract_jaaba_data <- function(dir_path,raw = FALSE) {
    i <- if_else(raw, 1, 4)
    jaaba_scores_files <- list.files(dir_path) %>% stringr::str_subset("scores_") %>% stringr::str_subset("_id_corrected.mat")
    for (ii in seq_along(jaaba_scores_files)) {
        if (ii == 1) {
            jaaba_scores <- list()
        }
        jaaba_scores_file <- R.matlab::readMat(paste0(dir_path,jaaba_scores_files[[ii]]))
        jaaba_behaviour <- jaaba_scores_files[[ii]] %>% stringr::str_remove("scores_") %>% stringr::str_remove("_id_corrected.mat")
        for (iii in 1:length(jaaba_scores_file[["allScores"]][[1]])) {
            if (iii == 1) {
                jaaba_scores_ind <- list()
            }
            jaaba_scores_ind[[iii]] <- tibble::tibble(Frame = 1:length(jaaba_scores_file[["allScores"]][[i]][[iii]][[1]][1,]),
                                             Fly_Id = iii,
                                             Behaviour = jaaba_behaviour,
                                             Value = jaaba_scores_file[["allScores"]][[i]][[iii]][[1]][1,]
            )
        }
        jaaba_scores[[ii]] <- dplyr::bind_rows(jaaba_scores_ind)
    }
    jaaba_scores <- dplyr::bind_rows(jaaba_scores)
    return(jaaba_scores)
}





