# Author: Aaron Munro Allen
# Date: 2021-11-15
# Description:
#   Function to extract data from the "track.mat" file generated by the Caltech FlyTracker
#   package written in Matlab. It may not matter, but this file assumes that "id_correction"
#   has been run from https://github.com/aaron-allen/goodwin-lab-tracking.


extract_track_data <- function(file_path) {
    
    ufmf_track <- R.matlab::readMat(file_path)
    
    # names
    for (i in seq_along(ufmf_track[["trk"]][[1]])) {
        if (i == 1) {
            track_names <- list()
        }
        track_names[[i]] <- ufmf_track[["trk"]][[1]][[i]][[1]][1,1]
    }
    track_names <- unlist(track_names)
    
    # flies.in.chamber
    for (i in seq_along(ufmf_track[["trk"]][[3]])) {
        if (i == 1) {
            fly_ids <- list()
        }
        fly_ids[[i]] <- tibble::tibble(Arena = rep(i,length(ufmf_track[["trk"]][[3]][[i]][[1]][1,])),
                               Fly_Id = ufmf_track[["trk"]][[3]][[i]][[1]][1,])
    }
    fly_ids <- dplyr::bind_rows(fly_ids)
    
    # data
    for (i in seq_along(track_names)) {
        if (i == 1) {
            track_data <- list()
        }
        for (ii in seq_along(fly_ids$Fly_Id)) {
            if (ii == 1) {
                track_data_feature <- list()
            }
            track_data_feature[[ii]] <- tibble::tibble(Fly_Id = fly_ids$Fly_Id[[ii]],
                                               Feature = track_names[[i]],
                                               Value = ufmf_track[["trk"]][[2]][ii,,i]
            )
        }
        track_data[[i]] <- dplyr::bind_rows(track_data_feature)
    }
    track_data <- dplyr::bind_rows(track_data)

    # flags
    
    # ...
    
    # pull together
    track_data <- dplyr::right_join(fly_ids,track_data, by = "Fly_Id")
    
    return(track_data)
}





